kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"redhat-airline-crewmember-api:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"redhat-airline-crewmember-api\")].image"}]
  name: redhat-airline-crewmember-api
  labels:
    app: redhat-airline
    app.kubernetes.io/name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redhat-airline
      deployment: redhat-airline-crewmember-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redhat-airline
        deployment: redhat-airline-crewmember-api
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: redhat-airline-airport-api
          image: >-
            image-registry.openshift-image-registry.svc:5000/redhat-airline/redhat-airline-crewmember-api:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: '8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

