kind: Service
apiVersion: v1
metadata:
  name: redhat-airline-airport-api
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: redhat-airline
    deployment: redhat-airline-airport-api
